name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 15 * *'

permissions:
  contents: read

jobs:
  compile_latex_and_upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@6549dc21effb2730855a1281407ecfcececc6c1b # v4
        with:
          root_file: main.tex

      - shell: bash
        run: |
          mv main.pdf thesis-example.pdf
        # rename is for backwards compatibility

      - name: Upload PDF artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          path: thesis-example.pdf
          name: thesis-example

  download_artifact_and_upload_release_asset:
    needs: compile_latex_and_upload_artifact # compilation must have completed successfully
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') # tags follow semantic versioning i.e. v0.2.1
    permissions:
      contents: write
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: thesis-example # same name as uploaded artifact

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          gh release create "$TAG_NAME" ./thesis-example.pdf \
            --title "$TAG_NAME" \
            --verify-tag
